aactual=2024
print('*'*50)
print(' DISEÑO TARJETA PRESENTACION '.center(50,'*'))
print('*'*50)
print()
nombre=input('Ingrese su nombre: ')
apellido=input('Ingrese su apellido: ')
a_nac=input('Ingrese año de nacimiento: ')
ciudad=input('Ingrese su ciudad de residencia: ')
apellido=apellido.upper()
nombre=nombre.capitalize()
ciudad=ciudad.upper()
i_nac=int(a_nac)
edad=aactual-i_nac
correo=nombre[0].lower()+apellido.lower()+'.'+a_nac+'@empresa.com.ar'
print()
print()
print(' TARJETA PRESENTACION '.center(60,'*'))
print('-'*60)
print(f'|   Apellido y nombre: {apellido}, {nombre}')
print(f'|   Año de nacimiento: {a_nac}')
print(f'|   Correo electronico: {correo}')
print(f'|   Ciudad: {ciudad}')
print(f'|   Edad aproximada: {edad}')
print('-'*60)
print()